services:   # elenco container da far partire

  rabbitmq:
    image: rabbitmq:3-management   # immagine RabbitMQ con dashboard
    ports:
      - "1883:1883"     # porta MQTT
      - "15672:15672"   # dashboard RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:   # prendi enabled_plugins e rendilo visibile al percorso /etc/rabbitmq/enabled_plugins nel container
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins

  producer:
    build: ./producer   # costruisci container partendo da dockerfile presente in sta cartella
    depends_on:
      - rabbitmq   # prima deve partire rabbitmq
    environment:
      MQTT_HOST: rabbitmq
      MQTT_PORT: 1883
      MQTT_USERNAME: guest
      MQTT_PASSWORD: guest
  
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_UTENTE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  consumer:
    build: ./consumer
    depends_on:
      - rabbitmq
      - postgres
    environment:
      MQTT_HOST: rabbitmq
      MQTT_PORTA: 1883
      MQTT_UTENTE: guest
      MQTT_PASSWORD: guest
      POSTGRES_HOST: postgres
      POSTGRES_PORTA: 5432
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_UTENTE: ${POSTGRES_UTENTE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8000:8000"